'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Modules.Keywordification

    Partial Public Class ViewKeywordification

        '''<summary>
        '''lblResponse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblResponse As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''imgAjax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgAjax As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''pnl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnl As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''jqgrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents jqgrid As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''jqpager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents jqpager As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
